### ISSUE TITLE
can't find the file:hla_ancillary_files/refseq.hg38.chr6.26000000.34000000.txt.gz

### ISSUE THREAD

**Issue by beifanglingyang** [rwdavies/QUILT#16]
Hi Robert,
 I tried to run the QUILT HLA reference panel construction example:https://github.com/rwdavies/QUILT/blob/master/example/QUILT_hla_reference_panel_construction.Md
But I could not find the file of gene information:--refseq_table_file=hla_ancillary_files/refseq.hg38.chr6.26000000.34000000.txt.gz .There are only three files in the directory "hla_ancillary_files":GRCh38_full_analysis_set_plus_decoy_hla.dict, hlagenes.txt, and quilt_hla_supplementary_info.txt.

I would like to know if I missed any information that prevents this file from being found.

Thanks so much!

**Comment by rwdavies** [comment]
Apologies, I had it in my local copy but forgot to push it. Should be there now.
Thanks,
Robbie

**Comment by beifanglingyang** [comment]
Thanks for your quick reply! Now, I can see the file ,so I'II close the issue.
                                                                                                                    Wei
