### ISSUE TITLE
Error encountered while running QUILT-HLA reference example

### ISSUE THREAD

**Issue by troyeeee** [rwdavies/QUILT#26]
Hello,

I encountered the following error while running the QUILT-HLA reference example:
![Screenshot_2023-05-19_15-19-53](https://github.com/rwdavies/QUILT/assets/33982960/96566bd2-c369-4f0e-9a37-e34cc1e0a468)

I would appreciate any guidance or suggestions on how to resolve this issue. Thank you for your support!

Best regards,
troye

**Comment by rwdavies** [comment]
Hi,

I assume this is bioconda, in which case, something has gone wrong with the version of samtools installed (must be very old if no version?). I'll investigate

Robbie

**Comment by rwdavies** [comment]
Hi,

Sorry for the delay. This was working in the latest release (1.0.4), but the bioconda version was old (1.0.3).The bioconda version is now updated to 1.0.3 and just worked in a test I ran, so should work for you. Let me know if you have any more problems. 

Thanks
Robbie
