### ISSUE TITLE
QUILT2_prepare_reference.R

### ISSUE THREAD

**Issue by PMuchina** [rwdavies/QUILT#37]
I was trying out QUILT2_prepare_reference.R and I ran into this error:
Error in QUILT_prepare_reference(outputdir = opt$outputdir, chr = opt$chr,  :
  object 'samtoolslike' not found
Calls: QUILT_prepare_reference -> <Anonymous>
I have not experienced such an error with QUILT1

**Comment by Zilong-Li** [comment]
Foremost, please show the command line and `seesionInfo()`! Second, was the `quick start example` running for you properly ?

I just updated the README where you can find important changes in QUILT2, i.e. only VCF file is supported through `QUILT2_preprare_reference`. 

Thanks for trying out QUILT2, while we're still working on improving the documentation.

**Comment by PMuchina** [comment]
.QUILT2_prepare_reference.R \
--genetic_map_file=genetic_map.txt \
--reference_vcf_file=Chr1_reference_panel.bcf \
--chr=Chr1 \
--nGen=100 \
--outputdir=quilt2_output

**Comment by PMuchina** [comment]
I havent tried he quick start example

**Comment by Zilong-Li** [comment]
Okay I see you are running for the whole chromosome which is not recommended. Can try running for a specific genomic region?

**Comment by PMuchina** [comment]
Okay, I will try that. Though it's an insect it's not that big.

**Comment by PMuchina** [comment]
I ran the whole chromosome on Quilt1 and I think it ran fine and I got some good results.

**Comment by Zilong-Li** [comment]
If you want to run whole chromosome, you can just set a big enough region, e.g. chr1:1-1000000000

**Comment by PMuchina** [comment]
Okay, ill try that

**Comment by PMuchina** [comment]
Thank you

**Comment by PMuchina** [comment]
I used QUILT::quilt_chunk_map to chunk my chromosomes. Then extracted start and end regions from this chunks and run build reference as below: 
QUILT2_prepare_reference.R \
    --outputdir="$Out_dir" \
    --chr="$Chr" \
    --nGen=100 \
    --regionStart="$regionStart" \
    --regionEnd="$regionEnd" \
    --buffer=500000 \
    --reference_vcf_file="$Ref_vcf" \
    --genetic_map_file="$Genetic_map" 

However, for each chunk for each chromosome, the genetic map is being read in for each chunk which takes a lot of time.

**Comment by rwdavies** [comment]
how long? I would have thought the genetic map reading part would be fast, while the VCF processing bit would be the slow part

**Comment by PMuchina** [comment]
Sorry, the issue was on my side. I was able to resolve this.

**Comment by PMuchina** [comment]
Thank you for your follow up.
