### ISSUE TITLE
Minimum reference panel size 

### ISSUE THREAD

**Issue by Matteo-Paini** [rwdavies/QUILT#40]
Hi, 
I was wondering if Quilt2 to work needs a minimium reference panel size, since the description says "with large reference panels".

Thank you in advance.

**Comment by Zilong-Li** [comment]
Hey,

QUILT2 can work with small reference panels as QUILT1. If the number of haplotypes `N` in the ref panel is smaller than the default value of option `K`, QUILT2/QUILT1 will just use all of them without selecting a subset.
