### ISSUE TITLE
Error in QUILT(outputdir = opt$outputdir, chr = opt$chr, method = opt$method

### ISSUE THREAD

**Issue by Emmafei** [rwdavies/QUILT#41]
Hi, I'm getting the following error when I'm using quilt1 for imputing, how can I fix this please, thanks a lot!
Error in QUILT(outputdir = opt$outputdir, chr = opt$chr, method = opt$method, ：
Parameter not used (method = opt$method, fflist = opt$fflist, n_burn_in_seek_its = opt$n_burn_in_seek_its, make_plots_block_gibbs = opt$make_plots_block_gibbs, reference_vcf_file = opt$reference_vcf_file、 small_ref_panel_block_gibbs_iterations = eval(parse(text = opt$small_ref_panel_block_gibbs_iterations)), small_ref_panel_gibbs_iterations = opt$small_ref_panel_gibbs_iterations、 mspbwtL = opt$mspbwtL, mspbwtM = opt$mspbwtM, use_mspbwt = opt$use_mspbwt, mspbwt_nindices = opt$mspbwt_nindices、 use_splitreadgl = opt$use_splitreadgl, override_use_eMatDH_special_symbols = opt$override_use_eMatDH_special_symbols, use_hapMatcherR = opt$use_hapMatcherR, shard_check_every_pair = opt$shard_check_every_pair, use_eigen = opt$use_eigen、 impute_rare_common = opt$impute_rare_common, rare_af_threshold = opt$rare_af_threshold, make_heuristic_plot = opt$make_heuristic_plot, heuristic_approach = opt$heuristic_approach, use_list_of_columns_of_A = opt$use_list_of_columns_of_A, calculate_gamma_on_the_f )

**Comment by Zilong-Li** [comment]
I kindly ask you provide more information. Also,  only QUILT2 supports NIPT imputation with fflist input. I am closing this now until you provide more information.

**Comment by Emmafei** [comment]
Hi, I'm getting the following error：
Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
sh q.sh
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   1.55 sec.
    Max Memory :                                 60 MB
    Average Memory :                             45.50 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   10 sec.
    Turnaround time :                            12 sec.

The output (if any) follows:

Error in QUILT(outputdir = opt$outputdir, chr = opt$chr, method = opt$method,  : 
  The parameters are not use(method = opt$method, fflist = opt$fflist, n_burn_in_seek_its = opt$n_burn_in_seek_its, make_plots_block_gibbs = opt$make_plots_block_gibbs, output_read_label_prob = opt$output_read_label_prob, reference_vcf_file = opt$reference_vcf_file, small_ref_panel_block_gibbs_iterations = eval(parse(text = opt$small_ref_panel_block_gibbs_iterations)), small_ref_panel_gibbs_iterations = opt$small_ref_panel_gibbs_iterations, mspbwtL = opt$mspbwtL, mspbwtM = opt$mspbwtM, use_mspbwt = opt$use_mspbwt, mspbwt_nindices = opt$mspbwt_nindices, use_splitreadgl = opt$use_splitreadgl, override_use_eMatDH_special_symbols = opt$override_use_eMatDH_special_symbols, use_hapMatcherR = opt$use_hapMatcherR, shard_check_every_pair = opt$shard_check_every_pair, use_eigen = opt$use_eigen, impute_rare_common = opt$impute_rare_common, rare_af_threshold = opt$rare_af_threshold, make_heuristic_plot = opt$make_heuristic_plot, heuristic_approach = opt$heuristic_approach, use_list_of_columns_of_A = o

and my command： 
outdir=quilt2_output && rm -rf $outdir
./QUILT2.R \
--outputdir=$outdir \
--method=nipt \
--chr=chr1 \
--bamlist=bam_list.txt \
--posfile=chr1position_info.txt \
--reference_vcf_file=10x.vcf.gz \
--nGen=100 \
--nCores=10 \
--save_prepared_reference=TRUE

Would appreciate any suggestions, or ideas, thanks!
