### ISSUE TITLE
output_read_label_prob misssing from the release 2.0.0 tarball

### ISSUE THREAD

**Issue by sounkou-bioinfo** [rwdavies/QUILT#43]
Hi,

When trying the example data, i get the error 
```Error in QUILT(outputdir = opt$outputdir, chr = opt$chr, method = opt$method,  : 
  unused argument (output_read_label_prob = opt$output_read_label_prob)
  
I check the release tarball, and the option is missing from the the R files. 
```
```
wget https://github.com/rwdavies/QUILT/releases/download/2.0.0/QUILT_2.0.0.tar.gz 
tar xf 
grep output_read_label_prob  QUILT/R/*R
```

Building and installing the package from the QUILT folder resolves the issue (QUILT 2.0.1).
The readme can be modify accordingly

**Comment by rwdavies** [comment]
@Zilong-Li are you OK to do the update?

**Comment by Zilong-Li** [comment]
Hey @sounkou-bioinfo,

I just made a new release v2.0.1. You can use the new version to obtain the final probability of each read label.
