### ISSUE TITLE
The invalid DS score

### ISSUE THREAD

**Issue by Mirror-fish** [rwdavies/QUILT#5]
Hello! I was doing 0.1x QUILT test using 1KG ref panel. This is the QUILT command:
> QUILT.R --outputdir ./no_map_chr3 \
--chr chr3 --regionStart=180000000 --regionEnd=190000000 --buffer=12500 \
--bamlist=./bam0.1.list \
--reference_haplotype_file=./chr3.hap.gz \
--reference_legend_file=./chr3.legend.gz \
--nGen=10 \

And when I got the vcf file, trying to recode it into traw using Plink 2.0:

> plink2 --recode A-transpose \
--vcf ./quilt.chr3.180000000.190000000.vcf.gz _**dosage=DS**_ \
--const-fid 0 --set-all-var-ids chr@:# \
--out ./quilt_0.1x_1kg

 An error happened:

> Error: Line 672 of --vcf file has an invalid DS field.

Then I found I line 672 a variant which DS score is 2.001:

> chr3 180392795 . G A . PASS EAF=0.98927;INFO_SCORE=0.07682;HWE=1.00e+00;ERC=3.99895;EAC=0.00035;PAF=0.99991 GT:GP:**_DS_**:HD 1|1:0.000,-0.001,1.001:**_2.001_**:1.002,1.000

I wonder how could this happen and how can I save it? Thanks.

**Comment by rwdavies** [comment]
What version is this? I fixed a bug recently that led to similar issues.
Assuming this is the previous version, I’m hoping the new version fixes
this issue?

**Comment by Mirror-fish** [comment]
Thanks! The problem fixed using 1.0.0 version!
